// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtfA1Hu68eQJSynTWkeWhNxsvUxN1YGAk',
    appId: '1:403987009448:web:9fc945c5291d0362c9179d',
    messagingSenderId: '403987009448',
    projectId: 'se7ety-125',
    authDomain: 'se7ety-125.firebaseapp.com',
    storageBucket: 'se7ety-125.firebasestorage.app',
    measurementId: 'G-RZ9FRHG571',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhPXo1DTF4Pxs53JsYQSJ4dp-cvzGTX08',
    appId: '1:403987009448:android:dea701778de7d344c9179d',
    messagingSenderId: '403987009448',
    projectId: 'se7ety-125',
    storageBucket: 'se7ety-125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvVhbLRoLbxUM6FDUeIpQM9ap0nKinKCc',
    appId: '1:403987009448:ios:97c383a632e491e2c9179d',
    messagingSenderId: '403987009448',
    projectId: 'se7ety-125',
    storageBucket: 'se7ety-125.firebasestorage.app',
    iosBundleId: 'com.aya.se7ety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvVhbLRoLbxUM6FDUeIpQM9ap0nKinKCc',
    appId: '1:403987009448:ios:97c383a632e491e2c9179d',
    messagingSenderId: '403987009448',
    projectId: 'se7ety-125',
    storageBucket: 'se7ety-125.firebasestorage.app',
    iosBundleId: 'com.aya.se7ety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtfA1Hu68eQJSynTWkeWhNxsvUxN1YGAk',
    appId: '1:403987009448:web:6df5c5d8dde17f14c9179d',
    messagingSenderId: '403987009448',
    projectId: 'se7ety-125',
    authDomain: 'se7ety-125.firebaseapp.com',
    storageBucket: 'se7ety-125.firebasestorage.app',
    measurementId: 'G-FKRWHDX6RM',
  );

}